### ISSUE TITLE
create sign up endpoint, sign up service layer, data-access layer, sign up repository for the sign up page   

### ISSUE THREAD

**Issue by jugginedwards** [BuildForSDGCohort2/Team-321-group-a-Backend#3]
On this project we'd be adopting various design patterns where necessary; 

We'd begin using the N-tier layered architectural pattern and then proceed to use the micro-services architecture.

Note: Sign up repository is the persistence layer for an N-tier architectural pattern;
It could be presented as a database or any other kind of data persistence network.

Way to go man! Up speed... lol

**Comment by gerryfrank10** [comment]
Okay @jugginedwards, i think by tomorrow everything is going to be just fine

**Comment by jugginedwards** [comment]
well done
